import type { Socio } from './soci-data';

// Note: The 'id' field will be ignored and auto-generated by Firestore.
// The 'status' is set to 'pending' as these are new requests.
export const sociDataSeed: Omit<Socio, 'id'>[] = [
    {
        "gender": "male",
        "firstName": "Andrea",
        "lastName": "Galli",
        "email": "andrea.galli@example.com",
        "phone": "3331112233",
        "birthPlace": "Firenze",
        "birthDate": "1992-07-21",
        "fiscalCode": "GLLNDR92L21H501A",
        "address": "Via della Musica 10",
        "city": "Firenze",
        "province": "FI",
        "postalCode": "50123",
        "requestDate": new Date().toISOString(),
        "status": "pending",
        "whatsappConsent": true,
        "privacyConsent": true
    },
    {
        "gender": "female",
        "firstName": "Sofia",
        "lastName": "Ricci",
        "email": "sofia.ricci@example.com",
        "phone": "3342233445",
        "birthPlace": "Bologna",
        "birthDate": "2009-03-15",
        "fiscalCode": "RCCSFO09C55A944B",
        "address": "Piazza Maggiore 5",
        "city": "Bologna",
        "province": "BO",
        "postalCode": "40124",
        "requestDate": new Date().toISOString(),
        "status": "pending",
        "whatsappConsent": true,
        "privacyConsent": true,
        "guardianFirstName": "Marco",
        "guardianLastName": "Ricci",
        "guardianBirthDate": "1980-01-01"
    },
    {
        "gender": "male",
        "firstName": "Matteo",
        "lastName": "Conti",
        "email": "matteo.conti@example.com",
        "phone": "3353344556",
        "birthPlace": "Torino",
        "birthDate": "1985-11-05",
        "fiscalCode": "CNTMRA85S05L219C",
        "address": "Corso Vittorio Emanuele 20",
        "city": "Torino",
        "province": "TO",
        "postalCode": "10123",
        "requestDate": new Date().toISOString(),
        "status": "pending",
        "whatsappConsent": false,
        "privacyConsent": true
    }
];
